name: Notify Homebrew Tap

on:
  release:
    types: [published]

jobs:
  notify-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to tap repo
        env:
          TAP_REPO: victorelgersma/homebrew-terminal-bookmarks
          GITHUB_TOKEN: ${{ secrets.TAP_REPO_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          TAR_URL="https://github.com/victorelgersma/terminal-bookmarks/archive/refs/tags/v${VERSION}.tar.gz"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/$TAP_REPO/dispatches \
            -d "{\"event_type\": \"update_formula\", \"client_payload\": {\"tarball_url\": \"${TAR_URL}\", \"version\": \"${VERSION}\"}}"